### PR TITLE
analyzer: make string concatenation optional

### LINKED ISSUE #21: Option to disable string addition warning
The string concatenation warning is useful, but there are times where `fmt.Sprintf` is more readable and performance is decent enough. One such example is in unit tests.

Ideally, the warning could be disabled based on file patterns (enforce only for runtime code), but a general flag would be sufficient too.

### PR DESCRIPTION
**Pull request by catenacyber**
Meant to fix #21 

@jalaziz what do you think of it ?

### CODE REVIEW

**Review by jalaziz — APPROVED** [review]
LGTM

**Comment by myouju** [comment]
@catenacyber Is it possible to create a release since this PR has been merged?

**Comment by catenacyber** [comment]
yes once #23 is fixed as well

**Comment by myouju** [comment]
I see. Thanks for your response.

**Comment by catenacyber** [comment]
v0.7.0 released cc @myouju

**Pull request merged**
